### ISSUE TITLE
Fields not showing in frontend

### ISSUE THREAD

**Issue by punani3000** [thejoshsmith/craft-fab-permissions#10]
Hi,

Some of the fields where no restrictions on permissions are set will not show up on the frontend if the user is not logged in. They are mainly asset (image) and entry fields. 

If I comment out line 102 in the file `src/services/Fab.php` everything works as expected:
`if( $user->getIsGuest() ) return false;`

Do you know why this might be the case? Is it save to comment out the line? 

Thanks

**Comment by thejoshsmith** [comment]
@punani3000 could you please install release `1.2.2` and let me know if this resolves your issue? I'll close this for now, but please reopen if it doesn't resolve your issue.
