### ISSUE TITLE
Craft 3.2.0 RC3 : Fatal Error in CP  : abstract methods not declared or implemented

### ISSUE THREAD

**Issue by ajoliveau** [thejoshsmith/craft-fab-permissions#3]
Hello,
After installing the plugin and adding some protected fields on an entry type, when logging in as a user in one of the restricted groups, I have the following error on some of the Control Panel pages : 

`PHP Fatal Error – yii\base\ErrorException
Class thejoshsmith\fabpermissions\decorators\StaticFieldDecorator contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (craft\base\FieldInterface::valueType, craft\base\FieldInterface::afterElementPropagate)`

If I manually add basic implementations for the two methods, it works : 
```
public function afterElementPropagate(ElementInterface $element, bool $isNew) {
    return;
}
public static function valueType() : string {
    return "test";
}
```

It affects the dashboard page (`/admin/dashboard`) and the Entry creation/modification page where the field with the permissions is located.

I'm running : 
- "craftcms/cms": "3.2.0-RC3"
- "thejoshsmith/craft-fab-permissions": "1.1.1"
- PHP 7.3
- No other plugins
- Vanilla Craft install with no other sections, fields or templates

It looks like these new methods have been added in Craft 3.2, as we can see in the history of the FieldInterface file : https://github.com/craftcms/cms/commits/3.2/src/base/FieldInterface.php

Thank you for this plugin !

**Comment by thejoshsmith** [comment]
Apologies—for some reason I didn't get a notification about this issue and just saw it. I'll have a look at your pull request shortly!

**Comment by thejoshsmith** [comment]
Cheers for finding and fixing this issue! I've tweaked your pull request slightly, but you did all the hard work in tracking it down 😄
