### ISSUE TITLE
Integrity constraint violation: 1048 Column 'canEdit' cannot be null

### ISSUE THREAD

**Issue by christianlemmers** [thejoshsmith/craft-fab-permissions#5]
So I've just installed this addon and added a field for testing. When setting permission I get the following error:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'canEdit' cannot be null
The SQL being executed was: INSERT INTO `fabpermissions_fieldlayoutpermissions` (`layoutId`, `tabId`, `fieldId`, `siteId`, `userGroupId`, `canView`, `canEdit`, `dateCreated`, `dateUpdated`, `uid`) VALUES (3, 22, NULL, 1, NULL, 1, NULL, '2019-08-13 08:01:12', '2019-08-13 08:01:12', '92572d30-9258-4956-8b64-2f3834b3637b'), (3, 22, NULL, 1, 1, 0, NULL, '2019-08-13 08:01:12', '2019-08-13 08:01:12', 'bb6ad2c4-d66b-45f5-a2d1-64b1ab216b6f'), (3, 22, NULL, 1, 2, 1, NULL, '2019-08-13 08:01:12', '2019-08-13 08:01:12', '2cd2d467-9656-4010-973f-64df368a225d')
Error Info: Array
(
    [0] => 23000
    [1] => 1048
    [2] => Column 'canEdit' cannot be null
)
```

I'm using Craft 3.2.9 in a Multi-Site configuration.

**EDIT: This only happens when changing permission to the field tabs.**

**Comment by thejoshsmith** [comment]
Thanks Christian, I’ll have a look into this shortly.

**Comment by thejoshsmith** [comment]
Apologies @christianlemmers for the delay, I've finally had a chance to sit down and resolve this! I made a slight architecture change a few versions ago and must've missed this one, so thanks for reporting. Let me know if version `1.1.3` works for you and I'll close this issue.

**Comment by thejoshsmith** [comment]
Closing as it's working for me now.
