### ISSUE TITLE
Front end loading issue

### ISSUE THREAD

**Issue by chenluu-strangeanimals** [thejoshsmith/craft-fab-permissions#6]
Hi, when removing view/edit permissions on a field. The front end website breaks.

Error : Call to a member function isInGroup() on null
File : src/services/Fab.php
Line : 118

Should it maybe be check $user->getIsGuest() before looping?

**Comment by thejoshsmith** [comment]
Thanks for reporting - I’ll have a look into this as soon as I can 🙂

**Comment by heggemsnes** [comment]
I get the same error when trying to load front end when not logged in.

**Comment by thejoshsmith** [comment]
Apologies for the delay @chenluu-strangeanimals and @heggemsnes, this now now be resolved in 1.1.4. Feel free to open another issue if you spot anything else.
