### ISSUE TITLE
Abstract method and must therefore be declared abstract or implement

### ISSUE THREAD

**Issue by godwinajit** [thejoshsmith/craft-fab-permissions#8]
Hi Received this error,

I guess this error happens when you give a user "Can View" permission for a field

PHP version	7.3.6
Database driver & version	MySQL 5.5.5
Craft edition & version	Craft Pro 3.3.4.1
Yii version	2.0.21
Field and Tab Permissions	1.1.4

PHP Fatal Error – yii\base\ErrorException
Class thejoshsmith\fabpermissions\decorators\StaticFieldDecorator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (craft\base\FieldInterface::getContentGqlType)

 in \vendor\thejoshsmith\craft-fab-permissions\src\decorators\StaticFieldDecorator.php
 
 <?php
 
namespace thejoshsmith\fabpermissions\decorators;
 
use thejoshsmith\fabpermissions\base\FieldDecorator;
use craft\base\ElementInterface;
use craft\base\FieldInterface;
 
class StaticFieldDecorator extends FieldDecorator {
 
    public function __construct(FieldInterface $field)
    {
    	return parent::__construct($field);
    }
 
    /**
     * Proxy all requests for input html to get static html
     * @author Josh Smith <me@joshsmith.dev>

yii\base\ErrorHandler::handleFatalError()

**Comment by thejoshsmith** [comment]
Thanks for reporting, I'll take a look at this tonight.

**Comment by thejoshsmith** [comment]
Hi @godwinajit, apologies for the delay in getting to this one. I've resolved the above issue in release `1.1.5`.

Please note I've also released version `1.2.0`, which requires you to override Craft's fields service in your app config (config/app.php) by adding:

```
'components' => [
   'fields' => [
      'class' => 'thejoshsmith\fabpermissions\services\Fields'
   ]
]
```

This change was made due to how project config listeners are registered, and for long term stability.

**Comment by godwinajit** [comment]
Hi @thejoshsmith I get a new error now 

> "[error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Getting unknown property: thejoshsmith\fabpermissions\FabPermissions::fabService"

See attached error.log file

[error.log](https://github.com/thejoshsmith/craft-fab-permissions/files/3714326/error.log)

When I delete all the fields assigned to the page the page launches , If I assign any field to to the page the page ( website ) crashes.

Application Info
PHP version	7.2.23
OS version	Linux 3.10.0-1062.1.1.el7.x86_64
Database driver & version	MySQL 5.5.5
Craft edition & version	Craft Pro 3.3.8
Yii version	2.0.21
Twig version	2.12.0


Plugins
Field and Tab Permissions	1.2.0
Forms	3.5.1
Navigation	1.1.13
Redactor	2.4.0
SEOmatic	3.2.28

**Comment by thejoshsmith** [comment]
Thanks @godwinajit, I've fixed this in release 1.2.1. I'll ensure testing the front end is part of my process going forward!

**Comment by godwinajit** [comment]
Thanks @thejoshsmith   I did a quick testing and it works fine now. 

I noticed something else in the Control Panel.

1. Go to Design your field layout for any entry
2. If you have set the permission for a field you can see a red dot near the gear icon for that field. If the permission is not set you do not see the red dot.
3. Not Click the Gear Icon -> Set Permission -> Clear ( You can see that the red dot is gone now )
4. Now Save the entry type
5. Now go back to the Edit entry type
6. You can see the red dot is back for the field which we cleared the permission and the permissions do not get cleared

Please let me know if you are also seeing this behavior. Let me know if you need more information on this.

**Comment by godwinajit** [comment]
Hi @thejoshsmith where you able to simulate the above mentioned scenario ?

**Comment by thejoshsmith** [comment]
Hi @godwinajit, no I haven't been able to sorry. If you send me a database dump to me@joshsmith.dev I can investigate for you. Alternatively, you could try uninstalling the plugin and re-installing?

**Comment by godwinajit** [comment]
Hi @thejoshsmith I tried  uninstalling the plugin and re-installing and it worked.

**Comment by godwinajit** [comment]
Hi @thejoshsmith I noticed an weird behavior after re-installing the plugin. Last time I verified the plugin in the admin panel and disabled it temporarily. Today I enabled it ( uninstalled and reinstalled as well ).  In the website front end if I am not logged in, the pages are not able to access the "entry" fields. Example I get the below error,

> Impossible to invoke a method ("one") on a null variable.

i.e the entry.fieldName is not accessible if I am not logged into the control panel. If I log into the control panel and open the website in a new tab , everything works fine.

PHP version | 7.3.9
-- | --
Linux 5.0.0-1018-azure
MySQL 5.5.5
GD 7.3.9
Craft Pro 3.3.13
Yii version 2.0.21
Twig version 2.12.1
Guzzle version 6.3.3
Imagine version 1.2.3-dev

Plugins
Element API	2.6.0
Entries Subset	1.2.2
Feed Me	4.1.2
Field and Tab Permissions	1.2.1
Forms	3.5.2
Navigation	1.1.13
Redactor	2.4.0
Redirect	3.1.26
SEO	3.2.28
Smart Map	3.2.2.1

**Comment by thejoshsmith** [comment]
Thanks for letting me know, I’ll look into this one tonight and get back to
you!

**Comment by thejoshsmith** [comment]
Hi @godwinajit, I wasn't able to replicate this issue. Could you please upload your web.log file so I can see the exact error you're getting?

For reference, I've created a test section and entry with fields, and am calling:

`{% set entry = craft.entries().section('testSection').one() %}`
`{{entry.email}}`

in the template. I am logged out when viewing the template.

**Comment by godwinajit** [comment]
[Copy of web.log](https://github.com/thejoshsmith/craft-fab-permissions/files/3779563/Copy.of.web.log)

@thejoshsmith Attached the log file . If I disable craft-fab-permissions plugin I do not get the error.
